import "@/src/Styles/global.css";
import { Metadata } from "next";
import { Providers } from "../lib/Provider";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className={`antialiased bg-[#020611] min-h-screen min-w-[100wh]`}>
        <Providers>
          <main className="container mx-auto sm:px-0">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
