import "@/src/Styles/global.css";
import { Metadata } from "next";
import { Providers } from "../lib/Provider";




export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
